Login
levydanqc/DeepRockGalactic pull request #13
Opened 2022-05-03 12:33 UTC by SimonLeger

2022-05-06 04:31 UTC, levydanqc requested changes

2022-05-06 04:31 UTC, levydanqc commented on backend/swagger-output.json
> -        "description": "Nécessite d'être de niveau 2",
Why did you delete this line ? If you didn't wanted to change this file you can remove it from this PR

2022-05-06 04:31 UTC, levydanqc commented on frontend/src/views/LoginView.vue
> +      <div style="width: 100%"></div>
Pretty much the same as signup around here, juste make sure not to use the 'style' attribute inside html and use bootstrap classes like you're currently doing !

2022-05-06 18:24 UTC, levydanqc requested changes

2022-05-06 18:24 UTC, levydanqc commented on yarn-error.log
> +Arguments:
This file shouldn't be here.

2022-05-06 18:24 UTC, levydanqc requested changes

2022-05-06 18:24 UTC, levydanqc commented on frontend/src/views/LoginView.vue
> +          console.log("data", data);
You should remove console statement as mentioned in the Github Action Warning juste below

2022-05-09 21:32 UTC, SimonLeger commented
I corrected everything, let me know if anything needs more attention

2022-05-09 23:09 UTC, levydanqc submitted a review, later dismissed
Perfect! I'll let you merge it (and don't forget to squash) 🥇

2022-05-10 02:28 UTC, levydanqc approved these changes

2022-05-12 18:30 UTC, merged